# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "i915.enable_guc=2"];
  boot.extraModulePackages = [ ];

  services.fwupd.enable = true;


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4eae03e1-51ae-48be-adf0-36d0070be0e0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ef510110-da22-41ba-a559-ede82faeae14".device = "/dev/disk/by-uuid/ef510110-da22-41ba-a559-ede82faeae14";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6641-9258";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
