keys:
  - &desktop age1e8mypfpuckp953wjmju2t5wnsf6t0nkh38gy5dh6e8cyxn9j8y9sl76zln
  - &ntoulapa age1g7skuvzvnnxl3ly7ku9cx6wuwtpysnlwxqzpdgde2ggqegdx038srxdvyl
  - &sfiri age12tw08w0gysx22m2mgp5s7az7yldttgqsk8x5p4pxpyucph9jtv0sml9287
  - &x1 age1h4urlkv3pwnz25sp5va374mtt4cjldq93mn4yw77hwpzcw0yhcpq7xkfu5
  - &xps age1jsef35sd02lahpyhy8pj4h4g5y895jmefpjc6yrkcw5vwzukeavqd63nz9
creation_rules:
  - path_regex: tf/secrets.yaml
    key_groups:
    - age:
      - *desktop
      - *x1
      - *xps
  - path_regex: secrets/digitalocean/secrets.yaml
    key_groups:
    - age:
      - *desktop
      - *ntoulapa
      - *sfiri
      - *x1
      - *xps
