# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "floppy" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];


  networking.useDHCP = lib.mkDefault true;
  networking.tempAddresses = "disabled";
  # networking.interfaces.ens14.useDHCP = lib.mkDefault true;
  boot.loader.grub.device = "/dev/vda";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c56516db-ec18-4750-a19b-95c1b3e5402e";
    fsType = "ext4";
  };
}
